### PR TITLE
Upgrade to v0.1.6 from v0.1.5

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by bgruening** [comment]
@dhimmel you need to at least change the checksum as well.

**Comment by dhimmel** [comment]
> @dhimmel you need to at least change the checksum as well.

Done in https://github.com/conda-forge/r-gdtools-feedstock/pull/1/commits/e20ff5e043c8c84e21763fdf4ca6099da406e831. Let me know if there are other things that will improve this PR... I'm not very familiar with the update process here

**Comment by jdblischak** [comment]
Thanks for the PR @dhimmel!

I noticed one additional thing. gdtools 0.1.6 added a minimum version dependency for rcpp. Could you please add ` >=0.12.12` to the `r-rcpp` line in both the build and run sections. It has to look like below (no space between the equal sign and version number):

```
    - r-rcpp >=0.12.12
```

https://cran.r-project.org/web/packages/gdtools/NEWS

**Comment by dhimmel** [comment]
@jdblischak @bgruening 🍏

**Comment by bgruening** [comment]
Here we go. Thanks!

**Comment by dhimmel** [comment]
@bgruening I'm surprised you didn't squash merge. I think you'll find squash merging will keep the commit history the most clean for pull requests such as these.

**Comment by bgruening** [comment]
I'm not sure there is a general recommendation. Other communities don't like Squash merging as it can hide the time/complexity which went into a PR. I can try to remember this and squash it next time.

**Comment by jdblischak** [comment]
> I'm surprised you didn't squash merge. I think you'll find squash merging will keep the commit history the most clean for pull requests such as these.

@dhimmel What I tend to do for small PRs like this one is to always amend the commit when I make a change based on feedback.

Also, for future PRs, please feel free to add yourself as a recipe maintainer.

**Pull request merged**
